# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6f030f8860825fb7ea1472256bf0aafb1a26c6b7e4f33b8f432c385c59b7fdf7d9b64b963a1e6ec8536eff1e4354794425e6b54c3d93ff215c9780815d2bd22

test:
  secret_key_base: a5fb04c5b31589249d8cf539dc17d9f702e4983224c08c89a61a0df3056edb5c86644a04dccf4b0f015e4759d310e2bbca4d35303aac325f7f5bde1b2279b2a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
